version: '3.8'

services:
  # Frontend Application
  pixel-detective-frontend:
    image: node:18-alpine
    container_name: pixel-detective-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    
  # Backend API
  pixel-detective-api:
    image: node:18-alpine
    container_name: pixel-detective-api
    ports:
      - "8000:8000" 
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev_user:dev_password@pixel-detective-db:5432/pixel_detective_dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - pixel-detective-db
      
  # Database
  pixel-detective-db:
    image: postgres:15-alpine
    container_name: pixel-detective-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pixel_detective_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  # Redis Cache
  pixel-detective-cache:
    image: redis:7-alpine
    container_name: pixel-detective-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 